version: '3'
services:
  frontend:
    build: .
    restart: always

  ## strapi
  strapi:
    image: strapi/strapi
    restart: always
    environment:
#      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    depends_on:
      - postgres
    #command: 'strapi build'
    #command: 'strapi start'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./strapi/postgres:/var/lib/postgresql/data

  ## ghost
  ghost:
    image: ghost:4-alpine
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      # this url value is just an example, and is likely wrong for your environment!
      url: http://ghost.svarun.lan
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ./ghost:/var/lib/ghost/content

networks:
  default:
    external:
      name: 02-proxy_default